[package]
name = "ch1"
version = "0.1.0"
edition = "2021"
authors = ["Choi Wheatley <chltmdgus604@naver.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
